name: nsysu_ap
description: NSYSU AP

version: 0.1.4+104

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  #official plugin
  shared_preferences: ^0.5.3+1
  package_info: ^0.4.0+4
  url_launcher: ^5.0.3
  firebase_core: ^0.4.0+3
  firebase_analytics: ^3.0.2
  firebase_remote_config: ^0.2.0+2
  firebase_messaging: ^5.0.2
  http: ^0.12.0+2
  html: ^0.14.0+2
  path_provider: ^1.2.0
  webview_flutter: 0.3.11+5

  #third party plugin
  toast: ^0.1.4
  encrypt: ^3.1.0
  cached_network_image: ^1.1.1
  carousel_slider: ^1.2.0
  flutter_local_notifications: ^0.6.1
  sprintf: ^4.0.2
  crypto: ^2.0.6
  flutter_crashlytics:
    path: ../flutter_crashlytics
  big5: 0.0.4
  printing: 2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/images/
